# Generated by Django 4.1.3 on 2022-12-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Final_project', max_length=255),
        ),
    ]
