# Generated by Django 4.1.3 on 2022-12-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
